### PR TITLE
Switch to Github Actions, Fix build, Remove Travis

### PR DESCRIPTION
**Pull request by ujovlado**
Changes:

- Switch to Github Actions
- Fix build (add custom sources.list, so it will build)
- Remove Travis
- Small cosmetic changes

---

Main thing is build/test on Github Actions

### CODE REVIEW

**Review by MiroCillik — APPROVED** [review]
LGTM

**Comment by odinuv** [comment]
Na co přesně je potřeba tohle buildovat ?

**Comment by ujovlado** [comment]
@odinuv je to kvoli https://github.com/keboola/orchestrator-router/pull/111

**Comment by ujovlado** [comment]
Tu je aj ta #14, takze to rovno mergnem.

**Pull request merged**
